version: "3.8"
services:
  rvc:
    build:
      context: .
      dockerfile: Dockerfile
    image: kennytat/rbvc-webui:latest
    container_name: rbvc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 1024m
    volumes:
      - ./assets:/app/assets
      - ./inference:/app/inference
      - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
      - ./logs:/app/logs
    ports:
      - 7865:7865
